name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o ${{ github.event.repository.name }}.exe .

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o ${{ github.event.repository.name }} .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: Release ${{ github.sha }}
          draft: false
          prerelease: false
          files: |
            ${{ github.event.repository.name }}.exe
            ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
